### ISSUE TITLE
Infrastructure - Test Result and Model Card Preview 

### ISSUE THREAD

**Issue by CodesAreHonest** [cylynx/verifyml-reports#1]
## Description 

1. Display test results with Github Actions.
2. Construct Model Card Viewer Link.
3. Publish Github Action to the Marketplace

## TODO 

* [x] 1. Allow user to customise which path the protobuf data is stored.
* [x] 2. Read the protobuf data and obtain the test results.
* [x] 3. Generate test result summary and print into the PR comments.
* [x] 4. Construct model card link.
* [x] 5. Publish the Github Action into Marketplace.
* [x] 6. Infrastructure and Setup.

## Questions 

1. Should we advise user to turn on their repository visibility to public?
2. The action should detect whether the repository is public or private, then guide user to upload their dataset to our Model Card Viewer when their repository is private.

## Notes

1. Require to generate Personal Access Token for actions to run. Refer [Link](https://github.com/nektos/act/issues/233#issuecomment-639348240)
2. https://www.npmjs.com/package/@actions/core
3. https://docs.github.com/cn/actions/creating-actions/publishing-actions-in-github-marketplace

**Comment by CodesAreHonest** [comment]
1. Infrastructure introduction and technical design decision.
2. Usage Demonstration.
3. Question and Answer.

**Comment by CodesAreHonest** [comment]
## TODO 

* [x] 1. change the model card viewer link with commit hash to gain the latest dataset.
* [x] 2. change description in the model card
* [x] 3. should not passed if any of the test case field.
